### ISSUE TITLE
Characterize the SED errors

### ISSUE THREAD

**Issue by tobias-liaudat** [tobias-liaudat/wf-SEDs#8]
### Part A: Generating the Ground Truth (GT)
- [x] Some high-resolved spectrum templates (sampling 1nm, 350 samples). Take as an example one position in the FOV. Generate a Super-Resolved (SR) polychromatic PSF for each of the spectrum templates (13 in total).

### Part B: Binning error
We want to see how much of the PSF error is coming from the binning.
- [x] Build SEDs with N bins (where N={8, 16, 32, 64}) from the spectrum templates.
- [x] Generate an SR polychromatic PSF for each template for each bin number.
- [x] Compare the reconstruction errors of the set of SR polychromatic PSF with respect to the GT for each bin number.

### Part C: Errors in the SEDs
We want to see how much the errors in the bins affect the PSF and compare it with the errors from the binning itself.
- [x] Consider the SEDs generated in the first point of part B. Add noise to each bin measurement to generate a noisy SED observation. The noise for each bin measurement can be drawn from a Gaussian distribution with zero mean and std dev :sigma:.
- [x] Generate 4 noisy SED bins [from :sigma_1: to :sigma_4: that _need to be defined_] for each SED dataset of N bins.
- [x] Compute the SR polychromatic PSFs for each of these noisy datasets.
- [x] Compute the errors between the generated SR polychromatic PSFs and the PSFs from part A and part B.

### Part D: Present results
We want to generate some plots that illustrate clearly the results obtained. For example (to be finished...):
- [x] Plot, x-axis (log-scale) the number of bins used (N), y-axis the reconstruction error with respect to the ground truth. The curve is done for the noiseless SEDs (part B).
- [x] Plot, x-axis (log-scale) the number of bins used (N), y-axis the reconstruction error with respect to the ground truth. In this case we will be plotting 4 curves, one for each :sigma: of the noisy dataset comparing the error with the GT.
- [x] Plot, x-axis (log-scale) the number of bins used (N), y-axis the reconstruction error with respect to the corresponding noiseless SED of N bins. In this case we will be plotting 4 curves, one for each :sigma: of the noisy dataset comparing the error with the noiseless SEDs.
- [x] Repeat the last two plots but now having in the x-axis the sigmas used for the introduction of noise, and having 4 curves, one for each N bins of the SEDs.

To express the reconstruction error it might be better to use the relative error.

### Documentation
- [x] Document and add plots to the WFE stage notes. Including links to the code used to generate the different things.

### ToDo to finish the study
@CentofantiEze 

- [x] Define which will be the default interpolation method for the SEDs bins. Especially, if we use `lineal` or `cubic`.
- [x] Do not do extrapolation in the SED interpolation. Leave out the points on the left of the first bin and on the right of the last bin.
- [x] Consider the error as being relative to the measurement. The assumption that the bins are 1/N does not hold!
- [x] Add two more values of small sigmas, e.g. `0.002` and `0.001`.
- [x] Interpolate SED to have 32 bins.

**Comment by tobias-liaudat** [comment]
Experience done and documented in section 3 of the overleaf.
